version: "3.8"

services:

  mongo:
    image: mongo
    container_name: mongo_bayeta
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bayeta_net

  bayeta:
    build: .
    container_name: bayeta_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - bayeta_net

networks:
  bayeta_net:
    driver: bridge

volumes:
  mongo_data:
